### ISSUE TITLE
Issue with running on different Linux distributions

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-standalone-apps#3]
The linux binary doesn't seem to work on all distributions - @Cadair got the following backtrace on ArchLinux and I get something similar on Fedora:

```
#0  0x00007ffff7f4c702 in raise () from /usr/lib/libpthread.so.0
#1  0x0000000000407766 in ?? ()
#2  0x000000000040417a in ?? ()
#3  0x00007ffff7d94b25 in __libc_start_main () from /usr/lib/libc.so.6
#4  0x000000000040254e in ?? ()
```

I tried making all the libraries be static with staticx but there are issues with PyQt5 that prevent this from running. We might need to make Linux binaries on different distributions using containers on GitHub actions.

**Comment by astrofrog** [comment]
Not building Linux apps anymore, so closing
