### ISSUE TITLE
Glue-viz not starting on Windows under Conda

### ISSUE THREAD

**Issue by kenlacrosse** [glue-viz/glue-standalone-apps#7]
About to try the standalone Windows Glue-viz installer and see if that works any better.

Under Conda I'm getting the following:
(base) C:\Users\klacrosse>glue -v
INFO:glue:Input arguments: ['C:\\ProgramData\\anaconda3\\Scripts\\glue', '-v']
INFO:glue:Loading external plugins using setuptools==65.6.3
INFO:glue:Loading plugin coordinate_helpers succeeded
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Scripts\glue-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\anaconda3\lib\site-packages\glue\main.py", line 259, in main
    start_glue(**kwargs)
  File "C:\ProgramData\anaconda3\lib\site-packages\glue\main.py", line 156, in start_glue
    load_plugins(splash=splash, require_qt_plugins=True)
  File "C:\ProgramData\anaconda3\lib\site-packages\glue\main.py", line 347, in load_plugins
    splash.set_progress(100. * iplugin / float(n_plugins))
  File "C:\ProgramData\anaconda3\lib\site-packages\glue\app\qt\splash_screen.py", line 31, in set_progress
    self.progress.setValue(value)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

(base) C:\Users\klacrosse>glue --version
1.2.4

(base) C:\Users\klacrosse>conda install -c glueviz -c conda-forge glueviz
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\anaconda3

  added / updated specs:
    - glueviz

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    glueviz-1.0.0              |                0          18 KB  glueviz
    ------------------------------------------------------------
                                           Total:          18 KB

The following packages will be SUPERSEDED by a higher-priority channel:

  glueviz               pkgs/main::glueviz-1.2.4-haa95532_0 --> glueviz::glueviz-1.0.0-0

Proceed ([y]/n)?

Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by kenlacrosse** [comment]
Standalone Windows (10) install succeeded and runs just fine.  Version info:
Glue: 1.7.0
Python: 3.8.10
PyQt5: PyQt: 5.14.2 - Qt: 5.14.2
PyQt6: Not installed
PySide2: Not installed
PySide6: Not installed
qtpy: 2.3.0
setuptools: 56.0.0
echo: 0.8.0
numpy: 1.21.6
matplotlib: 3.6.3
pandas: 1.5.3
astropy: 4.3.1
dill: 0.3.6
h5py: 3.8.0
xlrd: 2.0.1
openpyxl: 3.1.0
mpl-scatter-density: 0.7
glue-core: 1.7.0
glue-plotly: 0.4.0
glue-vispy-viewers: 1.0.7
glue-wwt: 0.6.1
IPython: 8.10.0
qtconsole: 5.4.0
ipykernel: 5.5.6
traitlets: 5.9.0
pygments: 2.14.0
pyzmq: 25.0.0
scipy: 1.10.0
scikit-image: Not installed
PyAVM: Not installed
spectral-cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: Not installed
plotly: 5.13.0

**Comment by Carifio24** [comment]
The error message in your first comment is the same one as in https://github.com/glue-viz/glue/pull/2266. Based on that, and the last upload date for glueviz on [Anaconda](https://anaconda.org/glueviz/glueviz), it looks like the version of glue available there predates that fix.

**Comment by kenlacrosse** [comment]
Guess Anaconda doesn’t keep their packages up to date then.  I’ll report it to them and see if they do anything.  Thanks.

Ken LaCrosse
Senior IT InfoSec and Infrastructure Monitoring Specialist
I.T. | American Recovery Service & Skipbusters
Direct:  (916) 260-4254
Cell: 916-635-8649
Email: ***@***.******@***.***>
www.pkwillis.com<http://www.pkwillis.com/>
